#!/bin/sh

INSTALL_STATIC=`pwd`/static
cd tinycc
make distclean
./configure --prefix=$INSTALL_STATIC
make
make install
cd ..

INSTALL_DYNAMIC=`pwd`/dynamic
cd tinycc
make distclean
./configure --prefix=$INSTALL_DYNAMIC --disable-static
make
make install
cd ..

