#!/bin/sh

INSTALL_STATIC=`pwd`/static
pushd tinycc
make distclean
./configure --prefix=$INSTALL_STATIC
make
make install
popd

INSTALL_DYNAMIC=`pwd`/dynamic
pushd tinycc
make distclean
./configure --prefix=$INSTALL_DYNAMIC --disable-static
make
make install
popd

