#pragma once

#define SIZE_MEMORY_CODE (65000)
#define SIZE_MEMORY_STATE (65000)
#define SIZE_MEMORY_AUDIO (65000)
#define NAME_MEMORY_CODE ("/code")
#define NAME_MEMORY_STATE ("/state")
#define NAME_MEMORY_AUDIO ("/audio")
#define NAME_SEMAPHORE_COMPILER_A ("/compiler_a")
#define NAME_SEMAPHORE_COMPILER_B ("/compiler_b")
#define NAME_SEMAPHORE_EXECUTER_A ("/executer_a")
#define NAME_SEMAPHORE_EXECUTER_B ("/executer_b")
#define NAME_SEMAPHORE_SUBMIT ("/submit")
#define NAME_SEMAPHORE_COMPILE ("/compile")
#define NAME_SEMAPHORE_SWAP ("/swap")

#define AUDIO_SAMPLERATE (48000.0)
#define AUDIO_FRAMECOUNT (512)
#define AUDIO_CHANNEL_OUT (2)
#define AUDIO_CHANNEL_IN (1)
#define AUDIO_PARAMETER_IN (2)
#define AUDIO_PARAMETER_OUT (2)
